/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const UserLazyImport = createFileRoute('/user')()
const MovieLazyImport = createFileRoute('/movie')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const UserLazyRoute = UserLazyImport.update({
  path: '/user',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/user.lazy').then((d) => d.Route))

const MovieLazyRoute = MovieLazyImport.update({
  path: '/movie',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/movie.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/movie': {
      preLoaderRoute: typeof MovieLazyImport
      parentRoute: typeof rootRoute
    }
    '/user': {
      preLoaderRoute: typeof UserLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  MovieLazyRoute,
  UserLazyRoute,
])

/* prettier-ignore-end */
