services:
  postgres:
    build:
      context: ./backend/.docker/postgres
      dockerfile: Dockerfile
    container_name: postgres
    volumes:
      - ./backend/.docker/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hal_cinema

  backend:
    build:
      context: ./backend/.docker/app
      dockerfile: local.Dockerfile
    container_name: backend
    platform: linux/amd64
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
  