/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as MoviesMovieIdRouteImport } from "./routes/movies/$movieId/route";

// Create Virtual Routes

const SchedulesRouteLazyImport = createFileRoute("/schedules")();
const ProfileRouteLazyImport = createFileRoute("/profile")();
const MoviesRouteLazyImport = createFileRoute("/movies")();
const HomeIndexLazyImport = createFileRoute("/_home")();
const GoogleCallbackRouteLazyImport = createFileRoute("/google/callback")();

// Create/Update Routes

const SchedulesRouteLazyRoute = SchedulesRouteLazyImport.update({
  path: "/schedules",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/schedules/route.lazy").then((d) => d.Route)
);

const ProfileRouteLazyRoute = ProfileRouteLazyImport.update({
  path: "/profile",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/profile/route.lazy").then((d) => d.Route)
);

const MoviesRouteLazyRoute = MoviesRouteLazyImport.update({
  path: "/movies",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/movies/route.lazy").then((d) => d.Route));

const HomeIndexLazyRoute = HomeIndexLazyImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/_home/route.lazy").then((d) => d.Route));

const GoogleCallbackRouteLazyRoute = GoogleCallbackRouteLazyImport.update({
  path: "/google/callback",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/google/callback/route.lazy").then((d) => d.Route)
);

const MoviesMovieIdRouteRoute = MoviesMovieIdRouteImport.update({
  path: "/$movieId",
  getParentRoute: () => MoviesRouteLazyRoute,
} as any).lazy(() =>
  import("./routes/movies/$movieId/route.lazy").then((d) => d.Route)
);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/movies": {
      id: "/movies";
      path: "/movies";
      fullPath: "/movies";
      preLoaderRoute: typeof MoviesRouteLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileRouteLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/schedules": {
      id: "/schedules";
      path: "/schedules";
      fullPath: "/schedules";
      preLoaderRoute: typeof SchedulesRouteLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/movies/$movieId": {
      id: "/movies/$movieId";
      path: "/$movieId";
      fullPath: "/movies/$movieId";
      preLoaderRoute: typeof MoviesMovieIdRouteImport;
      parentRoute: typeof MoviesRouteLazyImport;
    };
    "/google/callback": {
      id: "/google/callback";
      path: "/google/callback";
      fullPath: "/google/callback";
      preLoaderRoute: typeof GoogleCallbackRouteLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/_home/": {
      id: "/_home/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof HomeIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  MoviesRouteLazyRoute: MoviesRouteLazyRoute.addChildren({
    MoviesMovieIdRouteRoute,
  }),
  ProfileRouteLazyRoute,
  SchedulesRouteLazyRoute,
  GoogleCallbackRouteLazyRoute,
  HomeIndexLazyRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/movies",
        "/profile",
        "/schedules",
        "/google/callback",
        "/_home/"
      ]
    },
    "/movies": {
      "filePath": "movies/route.lazy.tsx",
      "children": [
        "/movies/$movieId"
      ]
    },
    "/profile": {
      "filePath": "profile/route.lazy.tsx"
    },
    "/schedules": {
      "filePath": "schedules/route.lazy.tsx"
    },
    "/movies/$movieId": {
      "filePath": "movies/$movieId/route.tsx",
      "parent": "/movies"
    },
    "/google/callback": {
      "filePath": "google/callback/route.lazy.tsx"
    },
    "/_home/": {
      "filePath": "_home/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
