services:
  postgres:
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    volumes:
      - .docker/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hal_cinema

  backend:
    build:
      context: .docker/app
      dockerfile: local.Dockerfile
    platform: linux/amd64
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - postgres