services:
  postgres:
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    volumes:
      - .docker/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hal_cinema

  migrate:
    build:
      context: .docker/migrate
      dockerfile: Dockerfile
    restart: "no"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=hal_cinema
    volumes:
    - ./:/migrate
    depends_on:
      - postgres
  
  backend:
    build:
      context: .docker/app
      dockerfile: local.Dockerfile
    platform: linux/amd64
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - migrate