// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMovieImage = "movie_images"

// MovieImage mapped from table <movie_images>
type MovieImage struct {
	MovieID  string `gorm:"column:movie_id" json:"movie_id"`
	FilePath string `gorm:"column:file_path;not null" json:"file_path"`
	Order    int32  `gorm:"column:order;not null" json:"order"`
}

// TableName MovieImage's table name
func (*MovieImage) TableName() string {
	return TableNameMovieImage
}
