// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrdersDetail = "orders_details"

// OrdersDetail mapped from table <orders_details>
type OrdersDetail struct {
	OrderDetailID   string `gorm:"column:order_detail_id;primaryKey" json:"order_detail_id"`
	OrderID         string `gorm:"column:order_id;not null" json:"order_id"`
	TheatersSeatsID string `gorm:"column:theaters_seats_id;not null" json:"theaters_seats_id"`
	PriceTypeID     string `gorm:"column:price_type_id;not null" json:"price_type_id"`
}

// TableName OrdersDetail's table name
func (*OrdersDetail) TableName() string {
	return TableNameOrdersDetail
}
