// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	OrderID   string    `gorm:"column:order_id;primaryKey" json:"order_id"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	IsPaid    bool      `gorm:"column:is_paid;not null" json:"is_paid"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
