// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTheater = "theaters"

// Theater mapped from table <theaters>
type Theater struct {
	TheaterID     string `gorm:"column:theater_id;primaryKey" json:"theater_id"`
	TheaterSizeID string `gorm:"column:theater_size_id;not null" json:"theater_size_id"`
	Name          string `gorm:"column:name;not null" json:"name"`
}

// TableName Theater's table name
func (*Theater) TableName() string {
	return TableNameTheater
}
