// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTheatersSeat = "theaters_seats"

// TheatersSeat mapped from table <theaters_seats>
type TheatersSeat struct {
	TheaterSeatID string `gorm:"column:theater_seat_id;primaryKey" json:"theater_seat_id"`
	OrderID       string `gorm:"column:order_id;not null" json:"order_id"`
	ScheduleID    string `gorm:"column:schedule_id;not null" json:"schedule_id"`
	SeatName      string `gorm:"column:seat_name" json:"seat_name"`
	PriceType     int32  `gorm:"column:price_type;not null" json:"price_type"`
}

// TableName TheatersSeat's table name
func (*TheatersSeat) TableName() string {
	return TableNameTheatersSeat
}
