// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTheatersSeat = "theaters_seats"

// TheatersSeat mapped from table <theaters_seats>
type TheatersSeat struct {
	TheaterSeatID string `gorm:"column:theater_seat_id;primaryKey" json:"theater_seat_id"`
	UserID        string `gorm:"column:user_id;not null" json:"user_id"`
	ScheduleID    string `gorm:"column:schedule_id;not null" json:"schedule_id"`
	SeatName      string `gorm:"column:seat_name;not null" json:"seat_name"`
}

// TableName TheatersSeat's table name
func (*TheatersSeat) TableName() string {
	return TableNameTheatersSeat
}
