// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID           string    `gorm:"column:user_id;primaryKey" json:"user_id"`
	FirstName        string    `gorm:"column:first_name" json:"first_name"`
	LastName         string    `gorm:"column:last_name" json:"last_name"`
	FirstNameReading string    `gorm:"column:first_name_reading" json:"first_name_reading"`
	LastNameReading  string    `gorm:"column:last_name_reading" json:"last_name_reading"`
	Email            string    `gorm:"column:email;not null" json:"email"`
	IconPath         string    `gorm:"column:icon_path" json:"icon_path"`
	Age              int32     `gorm:"column:age" json:"age"`
	Gender           int32     `gorm:"column:gender" json:"gender"`
	CreatedAt        time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	IsDelete         bool      `gorm:"column:is_delete;not null" json:"is_delete"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
