// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MovieImages struct {
	MovieID  *string `db:"movie_id" json:"movie_id"`
	FilePath string  `db:"file_path" json:"file_path"`
	Order    int32   `db:"order" json:"order"`
}

type Movies struct {
	MovieID       string `db:"movie_id" json:"movie_id"`
	Name          string `db:"name" json:"name"`
	Director      string `db:"director" json:"director"`
	Summary       string `db:"summary" json:"summary"`
	ThumbnailPath string `db:"thumbnail_path" json:"thumbnail_path"`
	Link          string `db:"link" json:"link"`
	// 上映時間
	Term        int32              `db:"term" json:"term"`
	ReleaseDate pgtype.Timestamptz `db:"release_date" json:"release_date"`
	EndDate     pgtype.Timestamptz `db:"end_date" json:"end_date"`
	IsDelete    bool               `db:"is_delete" json:"is_delete"`
}

type Orders struct {
	OrderID   string             `db:"order_id" json:"order_id"`
	UserID    string             `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type OrdersDetails struct {
	OrderDetailID   string `db:"order_detail_id" json:"order_detail_id"`
	OrderID         string `db:"order_id" json:"order_id"`
	TheatersSeatsID string `db:"theaters_seats_id" json:"theaters_seats_id"`
	PriceTypeID     string `db:"price_type_id" json:"price_type_id"`
}

type Permissions struct {
	PermissionID *string `db:"permission_id" json:"permission_id"`
	RoleID       string  `db:"role_id" json:"role_id"`
	Uri          string  `db:"uri" json:"uri"`
	ReqMethod    string  `db:"req_method" json:"req_method"`
	// 許可or不許可
	Effect bool `db:"effect" json:"effect"`
}

type PriceTypes struct {
	PriceTypeID string `db:"price_type_id" json:"price_type_id"`
	Name        string `db:"name" json:"name"`
	Price       int32  `db:"price" json:"price"`
}

type Roles struct {
	RoleID string `db:"role_id" json:"role_id"`
	Name   string `db:"name" json:"name"`
}

type Schedules struct {
	ScheduleID string             `db:"schedule_id" json:"schedule_id"`
	TheaterID  string             `db:"theater_id" json:"theater_id"`
	MovieID    string             `db:"movie_id" json:"movie_id"`
	StartDate  pgtype.Timestamptz `db:"start_date" json:"start_date"`
}

type Session struct {
	SessionID      *string            `db:"session_id" json:"session_id"`
	UserID         string             `db:"user_id" json:"user_id"`
	Token          string             `db:"token" json:"token"`
	ExpirationTime pgtype.Timestamptz `db:"expiration_time" json:"expiration_time"`
	RefreshToken   string             `db:"refresh_token" json:"refresh_token"`
}

type Theaters struct {
	TheaterID     string `db:"theater_id" json:"theater_id"`
	TheaterSizeID string `db:"theater_size_id" json:"theater_size_id"`
	Name          string `db:"name" json:"name"`
}

type TheatersSeats struct {
	TheaterSeatID string `db:"theater_seat_id" json:"theater_seat_id"`
	UserID        string `db:"user_id" json:"user_id"`
	ScheduleID    string `db:"schedule_id" json:"schedule_id"`
	SeatName      string `db:"seat_name" json:"seat_name"`
}

type TheatersSizes struct {
	TheaterSizeID string `db:"theater_size_id" json:"theater_size_id"`
	Name          string `db:"name" json:"name"`
	Capacity      int32  `db:"capacity" json:"capacity"`
}

type UserRoles struct {
	UserID    string             `db:"user_id" json:"user_id"`
	RoleID    string             `db:"role_id" json:"role_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Users struct {
	UserID           string             `db:"user_id" json:"user_id"`
	FirstName        string             `db:"first_name" json:"first_name"`
	LastName         string             `db:"last_name" json:"last_name"`
	FirstNameReading string             `db:"first_name_reading" json:"first_name_reading"`
	LastNameReading  string             `db:"last_name_reading" json:"last_name_reading"`
	Email            string             `db:"email" json:"email"`
	IconPath         *string            `db:"icon_path" json:"icon_path"`
	Age              int32              `db:"age" json:"age"`
	Gender           int16              `db:"gender" json:"gender"`
	PhoneNumber      string             `db:"phone_number" json:"phone_number"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	IsDelete         bool               `db:"is_delete" json:"is_delete"`
}
