import { Movie } from "./component/MovieColumn";

const data: Movie[] = [
  {
    id: "1",
    movieName: "クラメソ",
    releaseDate: "太郎",
    endDate: "kurameso.taro@example.com",
  },
  {
    id: "2",
    movieName: "クラメソ",
    releaseDate: "花子",
    endDate: "kurameso.hanako@example.com",
  },
  {
    id: "3",
    movieName: "くら",
    releaseDate: "にゃん",
    endDate: "kura.nyan@example.com",
  },
  {
    id: "4",
    movieName: "クラメソ",
    releaseDate: "二郎",
    endDate: "kurameso.jiro@example.com",
  },
  {
    id: "5",
    movieName: "クラメソ",
    releaseDate: "三郎",
    endDate: "kurameso.saburo@example.com",
  },
  {
    id: "6",
    movieName: "クラメソ",
    releaseDate: "四郎",
    endDate: "kurameso.siro@example.com",
  },
  {
    id: "7",
    movieName: "クラメソ",
    releaseDate: "五郎",
    endDate: "kurameso.goro@example.com",
  },
  {
    id: "8",
    movieName: "クラメソ",
    releaseDate: "六郎",
    endDate: "kurameso.rokuro@example.com",
  },
  {
    id: "9",
    movieName: "クラメソ",
    releaseDate: "七郎",
    endDate: "kurameso.shichiro@example.com",
  },
  {
    id: "10",
    movieName: "クラメソ",
    releaseDate: "八郎",
    endDate: "kurameso.hachiro@example.com",
  },
  {
    id: "11",
    movieName: "クラメソ",
    releaseDate: "九郎",
    endDate: "kurameso.kuro@example.com",
  },
  {
    id: "12",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "13",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "14",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "15",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "16",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "17",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "18",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "19",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "20",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "21",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "22",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "23",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "24",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "25",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "26",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "27",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "28",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "29",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
  {
    id: "30",
    movieName: "クラメソ",
    releaseDate: "XXXX",
    endDate: "kurameso.xxxx@example.com",
  },
];

export const getData: () => Promise<Movie[]> = async () => data;
