name: backend test

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'backend/**'
      - '.github/workflows/backend-test.yaml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-test.yaml'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./backend

# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        # refer: https://hub.docker.com/_/postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: hal_cinema_test
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'backend/go.mod'
        cache: true

    - name: write env
      run: |
        echo "${{ secrets.TEST_ENV }}" > .env.test
    
    - name: Install dependencies
      run: go mod download

    - name: migrate db
      run: |
        make migrate-up-test

    - name: set seeder
      run: go run cmd/seeder/main.go -e .env.test -f cmd/seeder/seeder.json

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./... -coverpkg=./... -v -json | go run github.com/mfridman/tparse@v0.13.2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: backend
        skip-pkg-cache: true
        args: --timeout=2m